# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rbcurse-experimental"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rahul Kumar"]
  s.date = "2013-04-23"
  s.description = "Ruby curses/ncurses widgets, experimental and minimally tested. Copy into your project, do not depend on this gem."
  s.email = "sentinel1879@gmail.com"
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "CHANGELOG",
    "README.markdown",
    "VERSION",
    "examples/teststackflow.rb",
    "lib/rbcurse/experimental/widgets/directorylist.rb",
    "lib/rbcurse/experimental/widgets/directorytree.rb",
    "lib/rbcurse/experimental/widgets/masterdetail.rb",
    "lib/rbcurse/experimental/widgets/multiform.rb",
    "lib/rbcurse/experimental/widgets/resultsetbrowser.rb",
    "lib/rbcurse/experimental/widgets/resultsettextview.rb",
    "lib/rbcurse/experimental/widgets/rscrollform.rb",
    "lib/rbcurse/experimental/widgets/stackflow.rb",
    "lib/rbcurse/experimental/widgets/tablewidget.rb",
    "lib/rbcurse/experimental/widgets/undomanager.rb",
    "rbcurse-experimental.gemspec"
  ]
  s.homepage = "http://github.com/rkumar/rbcurse-experimental"
  s.require_paths = ["lib"]
  s.rubyforge_project = "rbcurse"
  s.rubygems_version = "1.8.25"
  s.summary = "Ruby Ncurses Toolkit experimental widgets"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rbcurse-core>, [">= 0.0.3"])
      s.add_runtime_dependency(%q<rbcurse-extras>, [">= 0.0"])
    else
      s.add_dependency(%q<rbcurse-core>, [">= 0.0.3"])
      s.add_dependency(%q<rbcurse-extras>, [">= 0.0"])
    end
  else
    s.add_dependency(%q<rbcurse-core>, [">= 0.0.3"])
    s.add_dependency(%q<rbcurse-extras>, [">= 0.0"])
  end
end

